const shell = (title, body) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>${title} — The Flex Standard</title><style>body{margin:0;background:#0a0a0a;color:#ededed;font-family:system-ui,sans-serif;line-height:1.7}main{width:min(820px,calc(100% - 32px));margin:0 auto;padding:48px 0 72px}a{color:#d4af37}h1{font-size:clamp(2rem,7vw,3.5rem);line-height:1.05}h2{margin-top:2rem;color:#d4af37}p,li{color:#b8b8b8}.notice{border:1px solid #3b3420;background:#14120c;border-radius:16px;padding:18px}.back{display:inline-block;margin-bottom:28px;font-weight:800}</style></head><body><main><a class="back" href="/">← The Flex Standard</a>${body}</main></body></html>`;

export function healthDisclaimerPage() {
  return shell('Health & Fitness Disclaimer', `<h1>Health & Fitness Disclaimer</h1><p class="notice"><strong>The Flex Standard provides general fitness, wellness, motivational, and educational information. It is not medical advice and is not a substitute for care from a qualified healthcare professional.</strong></p><h2>Before You Begin</h2><p>Consult a qualified healthcare professional before beginning a new exercise, nutrition, or wellness program, especially if you have a medical condition, injury, are pregnant, take medication, have been inactive, or have any concern about whether an activity is appropriate for you.</p><h2>Listen to Your Body</h2><p>Exercise involves risk. Use appropriate modifications, work within your abilities, and stop immediately if you experience pain, dizziness, faintness, unusual shortness of breath, chest discomfort, or other concerning symptoms. Seek appropriate medical attention when needed.</p><h2>No Medical Relationship</h2><p>Use of this website, its challenges, emails, videos, or other materials does not create a doctor-patient, clinician-patient, or other healthcare professional relationship with The Flex Standard.</p><h2>Individual Results</h2><p>People respond differently to physical activity and habit programs. No specific health, fitness, weight, performance, or other result is promised or guaranteed.</p><h2>Your Responsibility</h2><p>You are responsible for deciding whether an activity is suitable for you, using safe technique and surroundings, following instructions from your healthcare professionals, and obtaining appropriate help when necessary.</p><p><em>Working operational draft. This page should receive qualified legal review before paid launch.</em></p>`);
}

export function privacyPage() {
  return shell('Privacy Policy', `<h1>Privacy Policy</h1><p class="notice"><strong>Plain-language working privacy notice for The Flex Standard.</strong></p><h2>Information You Choose to Provide</h2><p>If you voluntarily sign up, we may collect information such as your name, email address, challenge progress, and information needed to provide program access and communications. You may continue the free Foundation challenge without signing up; in that case, progress may remain only on your device.</p><h2>How We Use Information</h2><p>We use information to provide and improve the program, save and restore challenge progress, deliver requested challenge communications, provide customer support, protect the service, and understand how the service is used.</p><h2>Email</h2><p>If you provide your email for program communication, we may send challenge-related and program emails. Marketing email should include an unsubscribe method. We do not intend to send lifecycle email to visitors who do not provide an email address.</p><h2>Analytics and Advertising</h2><p>Before enabling analytics or advertising technologies that require consent, The Flex Standard intends to provide appropriate notice and consent controls. This policy must be updated to match the technologies actually enabled at launch.</p><h2>Payments</h2><p>When paid products are offered, payment processing may be handled by a third-party payment provider. The Flex Standard should not collect full payment-card details directly through its own challenge forms.</p><h2>Data Sharing</h2><p>We do not intend to sell personal information. Information may be processed by service providers needed to operate the service, subject to their roles and applicable requirements.</p><h2>Your Choices</h2><p>You can choose not to sign up for the free Foundation challenge. Where applicable, you may also unsubscribe from marketing email and exercise privacy rights provided by law.</p><p><em>Working operational draft. Final language must match the actual email, analytics, advertising, storage, payment, and consent systems before launch and should receive qualified legal review.</em></p>`);
}

export function termsPage() {
  return shell('Terms of Service', `<h1>Terms of Service</h1><p class="notice"><strong>Working operational terms for The Flex Standard.</strong></p><h2>Educational Program</h2><p>The Flex Standard provides general educational, motivational, fitness, and personal-development content. It does not provide medical diagnosis or treatment.</p><h2>Use of the Service</h2><p>Use the service lawfully and responsibly. Do not misuse the website, interfere with its operation, attempt unauthorized access, or copy and redistribute protected program materials except where permission is granted.</p><h2>Fitness Activities</h2><p>Participation is voluntary and at your own risk. Review the Health & Fitness Disclaimer and consult an appropriate healthcare professional when needed before beginning physical activity.</p><h2>Accounts and Access</h2><p>Some features may allow optional signup to save progress. Paid Mastery access, when launched, may require verified purchase and additional access controls.</p><h2>Digital Purchases</h2><p>Before paid Mastery launches, pricing, delivery, cancellation or refund terms, and any applicable purchase conditions will be displayed clearly before checkout. Those purchase terms must match the actual payment and delivery process.</p><h2>Intellectual Property</h2><p>The Flex Standard name, branding, original challenge materials, graphics, videos, and other original content are protected by applicable intellectual-property laws except where otherwise stated.</p><h2>No Guaranteed Results</h2><p>We do not guarantee particular fitness, health, financial, personal-development, or performance results.</p><h2>Changes</h2><p>These terms may be updated as the service changes. Material changes should be reflected on this page.</p><p><em>Working operational draft. Final terms should receive qualified legal review before paid launch.</em></p>`);
}

export function fitnessNotice() {
  return `<section style="max-width:900px;margin:24px auto;padding:16px 18px;border:1px solid #3b3420;border-radius:14px;background:#14120c;color:#b8b8b8;font-size:.9rem"><strong style="color:#d4af37">Health & Safety:</strong> The Flex Standard provides general fitness and educational information, not medical advice. Consult a qualified healthcare professional before beginning a new exercise program when appropriate for you, and stop exercising if you experience concerning symptoms. <a href="/health-disclaimer" style="color:#d4af37">Read the full disclaimer.</a></section>`;
}

export function legalFooter() {
  return `<footer style="border-top:1px solid #262626;margin-top:42px;padding:26px 16px;text-align:center;color:#888;font-size:.85rem"><div style="display:flex;gap:16px;justify-content:center;flex-wrap:wrap"><a href="/health-disclaimer" style="color:#d4af37">Health & Fitness Disclaimer</a><a href="/privacy" style="color:#d4af37">Privacy Policy</a><a href="/terms" style="color:#d4af37">Terms of Service</a></div><p style="margin-top:12px">© The Flex Standard. Focus. Learn. Execute. eXcel.</p></footer>`;
}