const LEGAL_CSS = `:root{--bg:#0f1115;--card:#1a1d24;--line:#2d3436;--gold:#c5a059;--text:#f5f5f5;--muted:#a7adb4}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,system-ui,-apple-system,sans-serif;line-height:1.7}.nav{display:flex;justify-content:space-between;gap:1rem;align-items:center;padding:1rem clamp(1rem,4vw,2rem);border-bottom:1px solid var(--line);background:#0f1115f2;position:sticky;top:0}.brand{color:var(--gold);font-weight:900;letter-spacing:.08em;text-decoration:none}.back{color:var(--muted);text-decoration:none;font-weight:800;font-size:.85rem}.wrap{width:min(860px,calc(100% - 2rem));margin:0 auto;padding:3rem 0 5rem}.badge{display:inline-block;border:1px solid #c5a05966;border-radius:999px;padding:.35rem .7rem;color:var(--gold);font-size:.72rem;font-weight:900;letter-spacing:.12em}h1{font-size:clamp(2.1rem,7vw,4rem);line-height:1.05;margin:.8rem 0 1.3rem;color:var(--gold)}h2{color:var(--gold);font-size:1.08rem;margin:1.65rem 0 .45rem}p,li{color:#d2d5d8}.card{background:var(--card);border:1px solid var(--line);border-radius:18px;padding:clamp(1.25rem,4vw,2.2rem)}ul,ol{padding-left:1.3rem}.note{color:var(--muted);font-size:.82rem;margin-top:2rem}.links{display:flex;gap:.8rem;flex-wrap:wrap;margin-top:1.4rem}.links a{color:var(--gold)}footer{text-align:center;border-top:1px solid var(--line);padding:2rem 1rem;color:#777;font-size:.8rem}`;

function shell(title, badge, body) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>${title} – The Flex Standard</title><style>${LEGAL_CSS}</style></head><body><header class="nav"><a class="brand" href="/">THE FLEX STANDARD</a><a class="back" href="/">← HOME</a></header><main class="wrap"><span class="badge">${badge}</span>${body}<div class="links"><a href="/disclaimer">Disclaimer</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div></main><footer>© 2026 The Flex Standard. All rights reserved.</footer></body></html>`;
}

export function disclaimerPage() {
  return shell('Health & Physical Activity Disclaimer', 'HEALTH & PHYSICAL ACTIVITY DISCLAIMER', `<h1>Participate Within Your Abilities.</h1><section class="card"><h2>Voluntary Participation & Assumption of Risk</h2><p>By engaging with The Flex Standard, including the 7-Day Foundation, 14-Day Momentum, and 21-Day Habit Lock challenges, you acknowledge that physical activity involves inherent risk. Participation is voluntary, and you are responsible for deciding whether an activity is appropriate for you.</p><h2>Educational Information — Not Medical Advice</h2><p>The Flex Standard provides general fitness, movement, habit, and personal-development information. It is not medical advice, diagnosis, treatment, or rehabilitation. Consider consulting a qualified healthcare professional before beginning a new exercise program, particularly if you have a medical condition, symptoms, an injury, are pregnant, take medication that may affect exercise, or have concerns about physical activity.</p><h2>Self-Monitoring</h2><p>Use appropriate modifications and work within your current abilities. Stop exercising and seek appropriate medical care if you experience chest pain, severe or unusual shortness of breath, fainting, severe dizziness, sudden weakness, or other concerning symptoms.</p><h2>Results & Responsibility</h2><p>Individual results vary. No specific health, fitness, weight, performance, or lifestyle result is guaranteed. The Flex Standard cannot evaluate your individual medical history, condition, equipment, or environment.</p></section><p class="note">This page provides general program disclosures and is not legal or medical advice.</p>`);
}

export function privacyPage() {
  return shell('Privacy Policy', 'PRIVACY POLICY', `<h1>Privacy Without the Fine-Print Maze.</h1><section class="card"><h2>Information We Collect</h2><p>We use data minimization. Depending on how you use the site, we may collect your name and email address, challenge progress and milestone records, local-storage state used to preserve progress on your device, and limited technical or usage information needed to operate and improve the service.</p><h2>How We Use Information</h2><ul><li>Deliver and manage The Flex Standard challenges and related digital content.</li><li>Preserve progress and unlock eligible challenge tiers.</li><li>Send requested or transactional program communications.</li><li>Protect, troubleshoot, measure, and improve the platform.</li></ul><h2>Service Providers & Analytics</h2><p>We may use service providers such as Cloudflare for hosting, database, and security functions and Brevo for email delivery and contact management. Advertising or analytics tools may be added or activated as the launch evolves; when used, associated disclosures and consent controls will be maintained as required.</p><h2>No Sale of Personal Information</h2><p>The Flex Standard does not sell, rent, or lease your personal information as a business model.</p><h2>Data Retention</h2><p>We retain information for as long as reasonably necessary to provide the requested service, maintain records, protect the platform, or meet applicable legal obligations.</p><h2>Your Choices</h2><p>You may unsubscribe from marketing communications using the unsubscribe mechanism in those messages. You may also request access, correction, or deletion of personal information where applicable.</p><h2>Contact</h2><p>Privacy questions or requests may be sent to privacy@theflexstandard.com.</p></section><p class="note">This policy may be updated as The Flex Standard adds or changes services, analytics, advertising, or account features.</p>`);
}

export function termsPage() {
  return shell('Terms of Service', 'TERMS OF SERVICE', `<h1>The Rules of the Standard.</h1><section class="card"><h2>Acceptance</h2><p>By accessing or using theflexstandard.com, you agree to these Terms of Service and applicable laws. If you do not agree, do not use the service.</p><h2>Free Challenge Access</h2><ol><li><strong>7-Day Foundation</strong> — introductory access to the core F.L.E.X. framework.</li><li><strong>14-Day Momentum</strong> — the next free challenge in the progression.</li><li><strong>21-Day Habit Lock</strong> — the final free challenge in the current launch funnel.</li></ol><p>28-Day Mastery and paid checkout remain separate from the current free V1 launch unless and until The Flex Standard explicitly makes them available.</p><h2>Educational Program</h2><p>The service provides general educational, fitness, movement, and personal-development content. It does not provide medical care or individualized professional advice.</p><h2>Intellectual Property</h2><p>The F.L.E.X. framework, Flex character assets, logos, copy, curriculum, designs, and instructional materials are owned by or licensed to The Flex Standard. You may use the service for personal, non-commercial purposes. Unauthorized copying, resale, or distribution is prohibited.</p><h2>User Conduct</h2><p>You agree not to misuse the site, interfere with its operation, transmit malicious code, attempt unauthorized access, or use the service for unlawful purposes.</p><h2>Future Paid Digital Products</h2><p>Terms specific to a future paid product, including price, access, refunds, and delivery, will be presented before purchase when paid products are activated. No paid Mastery checkout is part of the current free V1 launch.</p><h2>Availability & Changes</h2><p>Features may be updated, corrected, suspended, or changed as the service evolves. We may revise these terms and will publish the updated version on this page.</p><h2>Governing Law</h2><p>These terms are governed by the laws of the State of North Carolina, United States, without regard to conflict-of-law principles.</p><h2>Contact</h2><p>Legal inquiries may be sent to legal@theflexstandard.com.</p></section><p class="note">These terms are general operating terms for The Flex Standard V1 and are not a substitute for individualized legal advice.</p>`);
}
